version: '3'

services:
  api_diagnosis:
    container_name: api_diagnosis
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
